apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: RrAtELiMiT3r
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    is_default: true
    editable: false